destination: "public/data-schemas"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]

ga_tracking_code: "REPLACEME"

title: Open Data Schemas
root: "/data-schemas"
icon: fa fa-table
github_repo: https://github.com/open-data-standards/data-schemas
